additional_info: "문장 간 논리 관계 판별"
seed: 2025 # 42 # 115 # 2025
deterministic: false
hf_token: ""
use_lora: true
use_qlora: false
data_raw_dir: "datasets/converted_v2"
prompt_version: "sentence_relation"
data_question_length_limit: -1 # 800 # -1 means no limit
data_shuffle: true
data_hangul_info: false

# dpo 관련
# 기존의 sft 모델 경로
sft_model_for_dpo: ""

# only test
save_dir: "" # it will be set by the function
adapter_dir: "lora_adapter"
test_result_dir: "test_results"

is_cot: false
use_cache: true
sentence_relationship: true
span_extra_weight: 2 # 0 or 1~
